[tools]
fd = "10.4.2"
fzf = "0.74.2"
jq = "1.8.2"
ripgrep = "15.2.0"
xh = "0.26.2"

[bootstrap.packages]
"apk:ca-certificates" = "latest"
"apk:curl" = "latest"
"apk:git" = "latest"
"apk:neovim" = "latest"
"apk:nnn" = "latest"
"apk:zsh" = "latest"
"apt:ca-certificates" = "latest"
"apt:curl" = "latest"
"apt:git" = "latest"
"apt:neovim" = "latest"
"apt:nnn" = "latest"
"apt:zsh" = "latest"
"brew:ca-certificates" = { os = "macos" }
"brew:git" = { os = "macos" }
"brew:neovim" = { os = "macos" }
"brew:nnn" = { os = "macos" }
"brew:zsh" = { os = "macos" }
"dnf:ca-certificates" = "latest"
"dnf:curl-minimal" = "latest"
"dnf:git" = "latest"
"dnf:neovim" = "latest"
"dnf:nnn" = "latest"
"dnf:zsh" = "latest"

[bootstrap.hooks.pre-packages]
run = "../scripts/pre-packages.sh"
