#!/bin/sh
set -eu
config=${XDG_CONFIG_HOME:-$HOME/.config}/ds
kitty_bin=${MISE_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mise}/installs/http-kitty/latest/bin
[ -x "$kitty_bin/kitty" ] || {
	printf '%s\n' 'kt: install Kitty with ds apply ui' >&2
	exit 1
}
export PATH="$kitty_bin:$PATH"
exec "$config/kt" "$@"
